import { PassportTemplate } from '@/types'

export const PASSPORT_TEMPLATES: Record<string, PassportTemplate> = {
  DE: {
    code: 'DE',
    name: 'Germany',
    flag: '🇩🇪',
    widthMm: 35,
    heightMm: 45,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    headHeightMin: 0.70,
    headHeightMax: 0.80,
    eyeLineRatio: 0.45,
    background: 'white',
    note: 'ICAO 9303 · Biometric',
    requirements: [
      'Plain white or off-white background',
      'Head height 32–36 mm (70–80% of frame)',
      'Eyes open and clearly visible',
      'Neutral facial expression',
      'No shadows on face or background',
      'Printed size 35×45 mm',
    ],
  },
  FR: {
    code: 'FR',
    name: 'France',
    flag: '🇫🇷',
    widthMm: 35,
    heightMm: 45,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    headHeightMin: 0.70,
    headHeightMax: 0.80,
    eyeLineRatio: 0.45,
    background: 'white',
    note: 'ANTS · Biometric',
    requirements: [
      'White or very light gray background',
      'Head height 31–36 mm',
      'Eyes open, looking at camera',
      'No glasses',
      'Taken within 6 months',
      'Printed size 35×45 mm',
    ],
  },
  NL: {
    code: 'NL',
    name: 'Netherlands',
    flag: '🇳🇱',
    widthMm: 35,
    heightMm: 45,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    headHeightMin: 0.68,
    headHeightMax: 0.80,
    eyeLineRatio: 0.44,
    background: 'white',
    note: 'ICAO · RNI compliant',
    requirements: [
      'Plain white background',
      'Head 32–35 mm high',
      'Natural expression, mouth closed',
      'No head coverings (except religious)',
      'Sharp focus, no blur',
    ],
  },
  BE: {
    code: 'BE',
    name: 'Belgium',
    flag: '🇧🇪',
    widthMm: 35,
    heightMm: 45,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    headHeightMin: 0.70,
    headHeightMax: 0.80,
    eyeLineRatio: 0.45,
    background: 'white',
    note: 'ICAO · Biometric',
    requirements: [
      'White background',
      'Head centered and upright',
      'Eyes clearly visible',
      'Neutral expression',
    ],
  },
  ES: {
    code: 'ES',
    name: 'Spain',
    flag: '🇪🇸',
    widthMm: 32,
    heightMm: 26,
    widthPx: 378,
    heightPx: 307,
    dpi: 300,
    headHeightMin: 0.69,
    headHeightMax: 0.79,
    eyeLineRatio: 0.42,
    background: 'white',
    note: 'DNI · Passport format',
    requirements: [
      'White background',
      'Head 18–23 mm high',
      'Face occupies 70–80% of height',
      'Frontal view',
    ],
  },
  IT: {
    code: 'IT',
    name: 'Italy',
    flag: '🇮🇹',
    widthMm: 35,
    heightMm: 45,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    headHeightMin: 0.70,
    headHeightMax: 0.80,
    eyeLineRatio: 0.45,
    background: 'white',
    note: 'ICAO · Biometric',
    requirements: [
      'White or cream background',
      'Head 32–36 mm',
      'Natural expression',
      'No glasses since 2019',
    ],
  },
  GB: {
    code: 'GB',
    name: 'United Kingdom',
    flag: '🇬🇧',
    widthMm: 35,
    heightMm: 45,
    widthPx: 413,
    heightPx: 531,
    dpi: 300,
    headHeightMin: 0.70,
    headHeightMax: 0.80,
    eyeLineRatio: 0.45,
    background: 'light-gray',
    note: 'HMPO guidelines',
    requirements: [
      'Plain cream or light grey background',
      'Head 29–34 mm from chin to crown',
      'Eyes open and clearly visible at camera level',
      'Mouth closed, neutral expression',
      'Taken in the last month',
    ],
  },
  US: {
    code: 'US',
    name: 'United States',
    flag: '🇺🇸',
    widthMm: 51,
    heightMm: 51,
    widthPx: 600,
    heightPx: 600,
    dpi: 300,
    headHeightMin: 0.69,
    headHeightMax: 0.79,
    eyeLineRatio: 0.55,
    background: 'white',
    note: 'State Dept · 2×2 inch',
    requirements: [
      'Plain white or off-white background',
      'Head 1–1⅜ inches (25–35 mm) from chin to crown',
      'Taken within 6 months',
      'Full face, front view',
      'Neutral expression or natural smile',
      'No glasses since 2016',
    ],
  },
}

export const BG_OPTIONS = [
  { id: 'white' as const, label: 'White', hex: '#FFFFFF', border: '#E5E7EB' },
  { id: 'lightgray' as const, label: 'Light Gray', hex: '#F3F4F6', border: '#D1D5DB' },
  { id: 'lightblue' as const, label: 'Light Blue', hex: '#DBEAFE', border: '#BFDBFE' },
]

export const BG_HEX: Record<string, string> = {
  white: '#FFFFFF',
  lightgray: '#F3F4F6',
  lightblue: '#DBEAFE',
}

export const COUNTRY_SLUGS: Record<string, string> = {
  DE: 'germany',
  FR: 'france',
  NL: 'netherlands',
  BE: 'belgium',
  ES: 'spain',
  IT: 'italy',
  GB: 'united-kingdom',
  US: 'usa',
}
